name: test

on: [push, pull_request]

env:
  cache-version: v1

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: "Node ${{ matrix.node }} / ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x, 20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Run test
        run: |
          npm ci
          npm test
