name: test

on: [push, pull_request]

env:
  cache-version: v1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: "Node ${{ matrix.node }} / ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x, 20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Run test
        run: |
          npm ci
          npm test
